additionalHeaders = ["scripts/custom-header-style.toml"]

headerPath = "scripts/license-header.txt"

includes = [
    "*.pkl",
    "*.scm",
    "*.sh",
    "*.ts",
]

excludes = [
    "docs",
    "textmate-bundle"
]

[git]
attrs = 'auto'
ignore = 'auto'

[properties]
copyrightOwner = "Apple Inc. and the Pkl project authors"

[mapping.SCHEME_STYLE]
extensions = ["scm"]

#[mapping.PKL_STYLE]
#extensions = ["ts"]
